/**
 * Global application error codes for consistent backend responses.
 * These codes are machine-readable and used by the frontend for UI logic and translations.
 */
const ErrorCode = Object.freeze({
  // Authentication & Session Errors (401)
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_REVOKED_TOKEN: "AUTH_REVOKED_TOKEN",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_MFA_REQUIRED: "AUTH_MFA_REQUIRED",

  // Authorization & Permission Errors (403)
  AUTH_INSUFFICIENT_PERMISSIONS: "AUTH_INSUFFICIENT_PERMISSIONS",
  AUTH_RESOURCE_ACCESS_DENIED: "AUTH_RESOURCE_ACCESS_DENIED",

  // Request Validation Errors (400)
  VALIDATION_INVALID_EMAIL: "VALIDATION_INVALID_EMAIL",
  VALIDATION_PASSWORD_TOO_WEAK: "VALIDATION_PASSWORD_TOO_WEAK",
  VALIDATION_FIELD_REQUIRED: "VALIDATION_FIELD_REQUIRED",
  VALIDATION_FIELD_TOO_SHORT: "VALIDATION_FIELD_TOO_SHORT",
  VALIDATION_FIELD_TOO_LONG: "VALIDATION_FIELD_TOO_LONG",
  VALIDATION_INVALID_DATE: "VALIDATION_INVALID_DATE",
  VALIDATION_INVALID_SELECTION: "VALIDATION_INVALID_SELECTION",

  // Business Logic Constraints (400/404)
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_LIMIT_EXCEEDED: "RESOURCE_LIMIT_EXCEEDED",


  // Database conflict error (409)
  WRITE_CONFLICT_ERROR: "WRITE_CONFLICT_ERROR",

  // Payment & Billing Errors (402/400)
  PAYMENT_CARD_DECLINED: "PAYMENT_CARD_DECLINED",
  PAYMENT_INSUFFICIENT_FUNDS: "PAYMENT_INSUFFICIENT_FUNDS",
  PAYMENT_CARD_EXPIRED: "PAYMENT_CARD_EXPIRED",
  PAYMENT_INVALID_CVC: "PAYMENT_INVALID_CVC",
  PAYMENT_PROCESSING_FAILED: "PAYMENT_PROCESSING_FAILED",
  BILLING_SUBSCRIPTION_PAST_DUE: "BILLING_SUBSCRIPTION_PAST_DUE",

  // File Upload Errors (400/413)
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_UNSUPPORTED_TYPE: "FILE_UNSUPPORTED_TYPE",
  FILE_UPLOAD_CORRUPTED: "FILE_UPLOAD_CORRUPTED",

  // Email sending Errors (422)
  EMAIL_DELIVERY_REJECTED: "EMAIL_DELIVERY_REJECTED",

  // Rate Limiting & Integration Errors (429)
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  EXTERNAL_SERVICE_UNAVAILABLE: "EXTERNAL_SERVICE_UNAVAILABLE",

  // Internal Server Errors (500)
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR"
});

module.exports = { ErrorCode };
