/**
 * Global application error codes for consistent backend responses.
 * These codes are machine-readable and used by the frontend for UI logic and translations.
 */
const ErrorCode = Object.freeze({
  // Authentication Errors (401)
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_2FA_REQUIRED: "AUTH_2FA_REQUIRED",
  AUTH_2FA_INVALID: "AUTH_2FA_INVALID",
  AUTH_OAUTH_FAILED: "AUTH_OAUTH_FAILED",
  AUTH_OAUTH_EMAIL_CONFLICT: "AUTH_OAUTH_EMAIL_CONFLICT", // 409

  // Session & Token Errors (401/403)
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_REVOKED_TOKEN: "AUTH_REVOKED_TOKEN",
  AUTH_INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
  AUTH_REFRESH_TOKEN_REUSED: "AUTH_REFRESH_TOKEN_REUSED",
  AUTH_SESSION_LIMIT_REACHED: "AUTH_SESSION_LIMIT_REACHED", // 403

  // Authorization & Permission Errors (403)
  AUTH_INSUFFICIENT_PERMISSIONS: "AUTH_INSUFFICIENT_PERMISSIONS",
  AUTH_RESOURCE_FORBIDDEN: "AUTH_RESOURCE_FORBIDDEN",
  AUTH_CSRF_INVALID: "AUTH_CSRF_INVALID",
  AUTH_ORIGIN_NOT_ALLOWED: "AUTH_ORIGIN_NOT_ALLOWED",
  AUTH_REAUTH_REQUIRED: "AUTH_REAUTH_REQUIRED",

  // Account State Errors (403/409/410/423)
  ACCOUNT_EMAIL_NOT_VERIFIED: "ACCOUNT_EMAIL_NOT_VERIFIED",
  ACCOUNT_PHONE_NOT_VERIFIED: "ACCOUNT_PHONE_NOT_VERIFIED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED", // 410
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED", // 423
  ACCOUNT_ALREADY_VERIFIED: "ACCOUNT_ALREADY_VERIFIED", // 409
  ACCOUNT_EMAIL_TAKEN: "ACCOUNT_EMAIL_TAKEN", // 409
  ACCOUNT_USERNAME_TAKEN: "ACCOUNT_USERNAME_TAKEN", // 409

  // Password Errors (400)
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",
  PASSWORD_INCORRECT_CURRENT: "PASSWORD_INCORRECT_CURRENT",
  PASSWORD_SAME_AS_OLD: "PASSWORD_SAME_AS_OLD",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  PASSWORD_RESET_TOKEN_INVALID: "PASSWORD_RESET_TOKEN_INVALID",
  PASSWORD_RESET_TOKEN_EXPIRED: "PASSWORD_RESET_TOKEN_EXPIRED",
  PASSWORD_RESET_TOKEN_USED: "PASSWORD_RESET_TOKEN_USED",

  // Email Verification Errors (400)
  VERIFY_TOKEN_INVALID: "VERIFY_TOKEN_INVALID",
  VERIFY_TOKEN_EXPIRED: "VERIFY_TOKEN_EXPIRED",

  // OTP Errors (400/429/502)
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  OTP_ALREADY_USED: "OTP_ALREADY_USED",
  OTP_MAX_ATTEMPTS: "OTP_MAX_ATTEMPTS", // 429
  OTP_RESEND_TOO_SOON: "OTP_RESEND_TOO_SOON", // 429
  OTP_DAILY_LIMIT_REACHED: "OTP_DAILY_LIMIT_REACHED", // 429
  OTP_SEND_FAILED: "OTP_SEND_FAILED", // 502

  // Request Validation Errors (400/405/413/415/422)
  VALIDATION_FIELD_REQUIRED: "VALIDATION_FIELD_REQUIRED",
  VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",
  VALIDATION_OUT_OF_RANGE: "VALIDATION_OUT_OF_RANGE",
  VALIDATION_INVALID_ID: "VALIDATION_INVALID_ID",
  VALIDATION_UNPROCESSABLE: "VALIDATION_UNPROCESSABLE", // 422
  MALFORMED_JSON: "MALFORMED_JSON",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE", // 413
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE", // 415
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED", // 405
  PAGINATION_INVALID: "PAGINATION_INVALID",

  // File Upload Errors (400/413/415/502)
  FILE_REQUIRED: "FILE_REQUIRED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE", // 413
  FILE_TYPE_NOT_ALLOWED: "FILE_TYPE_NOT_ALLOWED", // 415
  FILE_TOO_MANY: "FILE_TOO_MANY",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED", // 502

  // Not Found Errors (404/410)
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  RESOURCE_GONE: "RESOURCE_GONE", // 410

  // Conflict Errors (409/412/422)
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  WRITE_CONFLICT_ERROR: "WRITE_CONFLICT_ERROR",
  RESOURCE_IN_USE: "RESOURCE_IN_USE",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  STALE_VERSION: "STALE_VERSION", // 412
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED", // 422

  // Rate Limiting & Quota Errors (429)
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",

  // Payment Errors (402/400/502) - optional
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  PAYMENT_CARD_DECLINED: "PAYMENT_CARD_DECLINED",
  PAYMENT_INSUFFICIENT_FUNDS: "PAYMENT_INSUFFICIENT_FUNDS",
  PAYMENT_CARD_EXPIRED: "PAYMENT_CARD_EXPIRED",
  PAYMENT_AUTHENTICATION_REQUIRED: "PAYMENT_AUTHENTICATION_REQUIRED",
  PAYMENT_PROCESSING_FAILED: "PAYMENT_PROCESSING_FAILED", // 502
  PAYMENT_WEBHOOK_INVALID: "PAYMENT_WEBHOOK_INVALID", // 400

  // Server & Infrastructure Errors (500/501/502/503/504)
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED", // 501
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR", // 502
  EXTERNAL_SERVICE_UNAVAILABLE: "EXTERNAL_SERVICE_UNAVAILABLE", // 503
  SERVICE_MAINTENANCE: "SERVICE_MAINTENANCE", // 503
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT", // 504
});

module.exports = { ErrorCode };
